### ISSUE TITLE
Crash with Vanilla Hud Plus 2 (Electric Crashaloo)

### ISSUE THREAD

**Issue by Bwamo** [HugoZink/IreNFist#105] opened 2021-03-07 17:04 UTC
Looks like I've found a new way to break IreNFist and VHP again and this time, it's through disabling Burst Mode in the hud mod.
Having Burst Mode off spits this out, but leaving it on works perfectly fine
```
Application has crashed: C++ exception
mods/IRE AND FIST REBORN/lua/playerstandard.lua:1077: attempt to call method 'in_burst_mode' (a nil value)



SCRIPT STACK

_update_check_actions() lib/units/beings/player/states/playerstandard.lua:948
original() lib/units/beings/player/states/playerstandard.lua:435
original() @mods/base/req/core/Hooks.lua:188
update_original() @mods/base/req/core/Hooks.lua:265
update() @mods/VanillaHUD Plus/lua/VanillaHUD.lua:958
original() lib/units/beings/player/playermovement.lua:271
@mods/base/req/core/Hooks.lua:265
```

**Comment by HugoZink** [comment] 2021-03-07 21:22
Confirmed, will fix for next release.

**Comment by Bwamo** [comment] 2021-03-10 21:46
looks like having [new classic enemies](https://modworkshop.net/mod/31263) even without vanilla hud plus will trigger the same exact error

**Comment by HugoZink** [comment] 2021-03-14 13:14
Looks like New Classic Enemies probably makes them use certain weapons that trigger the issue too. I've made a fix and will push it later today.

**Comment by HugoZink** [comment] 2021-03-14 16:11
Should be fixed.

**Closed by HugoZink** 2021-03-14 16:11 UTC
