### ISSUE TITLE
Breaching rounds not present

### ISSUE THREAD

**Issue by TaintedLion** [HugoZink/IreNFist#25] opened 2020-08-28 16:54 UTC
The modworkshop description states that shotguns have breaching rounds in this mod, I can't find them.

**Comment by HugoZink** [comment] 2020-08-28 23:00
They should be available on any shotgun, replacing the "free" version of 000 buckshot. Works for me. Do you have SuperBLT and Beardlib installed and the mod enabled?

**Comment by TaintedLion** [comment] 2020-08-28 23:18
I have all those things, its just that the description on modworkshop states that the breaching rounds can open anything a saw can, yet they can't open metal doors or safe deposit boxes.

**Comment by Bwamo** [comment] 2020-08-29 01:03
Seems to work fine on my end
![20200828210236_1](https://user-images.githubusercontent.com/23544898/91625006-df96ce00-e971-11ea-88ec-6425a0e70a1b.jpg)
![20200828210240_1](https://user-images.githubusercontent.com/23544898/91625011-e58caf00-e971-11ea-89c2-e8bae0c7beef.jpg)

**Comment by TaintedLion** [comment] 2020-08-29 01:04
![image](https://user-images.githubusercontent.com/22858358/91625031-f18d6680-e99b-11ea-847b-b16ac7184de6.png)

So is it the triple ought buck?

**Comment by Bwamo** [comment] 2020-08-29 01:15
AA-12 has breaching rounds on my end.
![20200828211445_1](https://user-images.githubusercontent.com/23544898/91625229-8d56ac80-e973-11ea-9542-4c0e7b3de25d.jpg)

**Comment by TaintedLion** [comment] 2020-08-29 01:18
idk then

**Comment by TaintedLion** [comment] 2020-08-29 01:19
i have beardlib and weaponlib and superblt

**Comment by HugoZink** [comment] 2020-08-29 11:22
No, it's not 000 buckshot. It adds "breaching rounds". It seems that one of your 000 buckshot variants is missing.

If you have any mods that remove this variant then you won't be able to use breaching rounds. What other mods do you have installed? One of them is removing this, probably as a "QoL feature".

Either way the issue is definitely not on my end. I'll close this issue as invalid, but I'll keep watching it.

**Closed by HugoZink** 2020-08-29 11:22 UTC

**Comment by HugoZink** [comment] 2020-08-29 11:25
@TaintedLion it looks like WolfHud is probably the issue. If you can't turn this feature off in the WolfHUD options, I recommend removing the mod. It's bad anyway.

I'll make sure to include a compatibility warning for WolfHUD too then. Thanks.

**Comment by TaintedLion** [comment] 2020-08-29 13:23
what hud are you using?
