### ISSUE TITLE
akimbo weapons no recoil

### ISSUE THREAD

**Issue by Coremanite** [HugoZink/IreNFist#112] opened 2021-05-26 12:51 UTC
all akimbo weapons appear to have no recoil at all.

**Comment by HugoZink** [comment] 2021-05-29 22:52
Will look into it.

**Comment by HugoZink** [comment] 2021-05-31 12:54
Akimbo weapon recoil works fine on my end. This is probably a mod compatibility issue - I'm interested in making it compatible, but I don't know *which* mod it is. You'll have to either post your modlist, or figure out which mod is causing it through trial and error.

Note that most other skill overhauls are currently not compatible. SSO changes too fast for me to keep up with, and the fact that it uses BeardLib's hooks means I cannot realistically make it compatible on every front.

**Comment by HugoZink** [comment] 2021-05-31 13:11
There are some mods that change akimbos to only fire once per click (some HUD mods do this, weirdly enough). That's the most likely culprit, as InF only applies recoil on the second shot. If you have any such mods, list them and I can try to make them compatible.

**Comment by HugoZink** [comment] 2021-06-04 11:37
Since I wasn't able to reproduce this, I'm closing the issue for now since I suspect it is a mod compatibility issue.

If you _do_ figure out which mod is causing this, feel free to comment and I can re-open the issue.

**Closed by HugoZink** 2021-06-04 11:37 UTC
