### ISSUE TITLE
still dosent work, sending you newest crash file 

### ISSUE THREAD

**Issue by thic9000** [HugoZink/IreNFist#15] opened 2020-08-16 16:37 UTC
[payday2_win32_release_5412799_crash_2020_8_16T16_36_28C0.txt](https://github.com/HugoZink/IreNFist/files/5081002/payday2_win32_release_5412799_crash_2020_8_16T16_36_28C0.txt)

**Comment by HugoZink** [comment] 2020-08-16 16:56
Most likely another mod incompatibility. I'll fix it.

Sorry for playing whack-a-mole here, it's just that so many of these custom weapons were changed in the past and that's now causing crashes. I don't have time to check them all by hand myself.

**Comment by HugoZink** [comment] 2020-08-16 16:59
I should also mention that you seem to have a lot of mods installed that might not necessarily work with IREnFIST, including Bipods That Work and some LMG rebalance mod. While this is *not* the cause of your current crashes, I recommend removing or disabling those as IREnFIST already fixes that.

**Comment by HugoZink** [comment] 2020-08-16 17:02
Fixed in f5da89c7ef0b245b3012821416b8c20786aed5b6.

**Closed by HugoZink** 2020-08-16 17:02 UTC
Labels: bug, mod compatibility

**Comment by thic9000** [comment] 2020-08-16 17:53
okay and dont be sorry if i can help you fixing stuff its perfectly fine
and you are doing a great job
