### ISSUE TITLE
ST AR-15 - what "High velocity rounds" actually are?

### ISSUE THREAD

**Issue by MrVavlo** [HugoZink/IreNFist#57] opened 2020-10-05 17:10 UTC
I believe it should have upgrade this weapon to 280 damage tier, but at the end it have 240 and lower total ammo than others' rifles

![20201005200341_1](https://user-images.githubusercontent.com/34880333/95109906-e8837800-0745-11eb-9fc0-bc8bb4865844.jpg)
(Consumer-Grade Rounds are fine, I guess)

And that's the last weapon from me. Didn't find any issues on others non-hidden custom weapons ^^ (godwhatabiglistitwas)
There's also the problem with Steyr AUG A3 9mm XS, but I don't know if it's IreNFist problem or something else comes in and mess with its base stats, so I'll leave it behind.

**Comment by HugoZink** [comment] 2020-10-05 18:04
The ST AR-15 High-Velocity rounds are working as intended. I had to create a new "Heavy DMR" class specifically for this beautiful little thing.

I'm running into some issues with bounded stats and indexes, meaning I cannot actually hit 280 damage properly on an AR. This will be revisited at some point, but right now the weapon should be perfectly usable.

**Comment by MrVavlo** [comment] 2020-10-05 18:46
Nah, if it stays as DMR, then I have no any suggestions except raising total ammo, even with 240 damage. 
I genially thought this ammo type is an upgrade to sniper rifle tier, but this can work too. =)

**Comment by HugoZink** [comment] 2020-10-11 15:53
Should be fixed.

**Closed by HugoZink** 2020-10-11 15:53 UTC
Labels: enhancement
